#!/bin/bash
export NEWT_COLORS="root=,black"
txtmainmenu="Test Menu Dialog"
OPTION=$(whiptail --title "${txtmainmenu}" --default-item "${nextitem}" --menu  "Choose your option" 15 60 4 \
"" "Grilled Spicy Sausage"  \
"" "Grilled Halloumi Cheese" \
"" "Charcoaled Chicken Wings" \
"" "Fried Aubergine"  3>&1 1>&2 2>&3)
 
exitstatus=$?
if [ $exitstatus = 0 ];  then
     case ${OPTION} in
			"${txtlanguage}")
				chooselanguage
				nextitem="${txtsetkeymap}"
			;;
			"${txtsetkeymap}")
				setkeymap
				nextitem="${txtdiskpartmenu}"
			;;
			"${txteditor}")
				chooseeditor
				nextitem="${txtdiskpartmenu}"
			;;
		esac
		else
		clear
	fi