#!/bin/bash
mainmenu(){
     export NEWT_COLORS="root=,black"
	if [ "${1}" = "" ]; then
		nextitem="."
	else
		nextitem=${1}
	fi
	options=()
	options+=("${txtlanguage}" "Language")
	options+=("${txtsetkeymap}" "(loadkeys ...)")
	options+=("${txteditor}" "(${txtoptional})")
	options+=("${txtdiskpartmenu}" "")
	options+=("${txtselectpartsmenu}" "")
	options+=("" "")
	options+=("${txtreboot}" "")
	sel=$(whiptail --title "Welcome GPG-FIX !" --cancel-button "${txtexit}" --default-item "${nextitem}" --menu "" 0 0 0 \
		"${options[@]}" \
		3>&1 1>&2 2>&3)
	if [ "$?" = "0" ]; then
		case ${sel} in
			"${txtlanguage}")
				chooselanguage
				nextitem="${txtsetkeymap}"
			;;
			"${txtsetkeymap}")
				setkeymap
				nextitem="${txtdiskpartmenu}"
			;;
			"${txteditor}")
				chooseeditor
				nextitem="${txtdiskpartmenu}"
			;;
			"${txtdiskpartmenu}")
				diskpartmenu
				nextitem="${txtselectpartsmenu}"
			;;
			"${txtselectpartsmenu}")
				selectparts
				nextitem="${txtreboot}"
			;;
			"${txthelp}")
				help
				nextitem="${txtreboot}"
			;;
			"${txtchangelog}")
				showchangelog
				nextitem="${txtreboot}"
			;;
			"${txtreboot}")
				rebootpc
				nextitem="${txtreboot}"
			;;
		esac
		mainmenu "${nextitem}"
	else
		clear
	fi
}
if [ "${chroot}" = "1" ]; then
	case ${command} in
	esac
else
	loadstrings
	mainmenu
fi
loadstrings(){
txtexit="Отмена"
}