#!/bin/bash
#window=$(stty -a | tr \; \\012 |grep -E 'rows|columns' | cut '-d ' -f3)
export NEWT_COLORS="root=,black"
OPTION=$(whiptail --title  "Welcome GPG-FIX !" --menu "" 0 0 0 \
"1" "Fix GPG Manjaro" \
"2" "Fix GPG Manjaro + Chaotic" \
"3" "Fix GPG Manjaro + BlackArch" \
"4" "Fix GPG Manjaro + Chaotic + BlackArch"  3>&1 1>&2 2>&3 )
 
exitstatus=$?
if [ $exitstatus = 0 ];  then
     echo "Your chosen option:" $OPTION
else
     echo "You chose Cancel."
fi