#!/bin/bash
#systemctl start pacman-init.service
OPTION=$(whiptail --title  "Test Menu Dialog" --nocancel $window 20 \
"1" "Grilled Spicy Sausage" \
"2" "Grilled Halloumi Cheese" \
"3" "Charcoaled Chicken Wings" \
"4" "Fried Aubergine"  3>&1 1>&2 2>&3)
 
exitstatus=$?
if [ $exitstatus = 0 ];  then
     echo "Your chosen option:" $OPTION
else
     echo "You chose Cancel."
fi
